version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"  # Expose frontend internally

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"  # Expose backend internally

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Expose Nginx on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend