version: "3.8"
services:
  frontend:
    build:
      context: ./frontend  # Path to your React Vite project
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map host port 80 to container port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to your FastAPI project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000